[features]
seeds = false
[programs.localnet]
staking = "4q9ZkdHGrUy9jiaYLCYhwPP64K67Y64mhwYS1yKJaXCE"
token_sale = "CKtaZDifHb9EbhW9StG42FuR673mQykFFPDEST4h2rhB"
vesting = "2btf863eSGk6bhBTm4GQ628uBsHJdfS86iWkDA9GfqzB"
whitelist_nft = "6HiU5wq8x4gSh8GLyN5oxEtubJw1ArPS5gx72zM76FW2"
[programs.devnet]
staking = "4q9ZkdHGrUy9jiaYLCYhwPP64K67Y64mhwYS1yKJaXCE"
token_sale = "CKtaZDifHb9EbhW9StG42FuR673mQykFFPDEST4h2rhB"
vesting = "2btf863eSGk6bhBTm4GQ628uBsHJdfS86iWkDA9GfqzB"
whitelist_nft = "6HiU5wq8x4gSh8GLyN5oxEtubJw1ArPS5gx72zM76FW2"
[programs.testnet]
staking = "4q9ZkdHGrUy9jiaYLCYhwPP64K67Y64mhwYS1yKJaXCE"
token_sale = "CKtaZDifHb9EbhW9StG42FuR673mQykFFPDEST4h2rhB"
vesting = "2btf863eSGk6bhBTm4GQ628uBsHJdfS86iWkDA9GfqzB"
whitelist_nft = "6HiU5wq8x4gSh8GLyN5oxEtubJw1ArPS5gx72zM76FW2"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/user/.config/solana/id.json"

[test]
startup_wait = 10000

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
